{"name": "Login fail - username: bob@example.com", "status": "passed", "attachments": [{"name": "log", "source": "93c5a4e6-c989-4565-9b0f-671ae1c070a3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'bob@example.com'"}, {"name": "password", "value": "'1111'"}, {"name": "expected", "value": "{'error': 'Provided credentials do not match any user in this service.'}"}], "start": 1757311226376, "stop": 1757311231734, "uuid": "ad359ee5-2379-41c0-b241-3642fc9ff87d", "historyId": "3ee81cf7dd34693cfb47f7631ec08913", "testCaseId": "7b6113008a0e4d8a5bad2235a270375d", "fullName": "tests.test_login.TestLogin#test_login_fail", "labels": [{"name": "story", "value": "Login fail"}, {"name": "feature", "value": "Login Flow"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBookPro"}, {"name": "thread", "value": "60465-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py", "TestLogin"]}